### ISSUE TITLE
Question about Equation 7 and Figure 4

### ISSUE THREAD

**Issue by cuge1995** [dogyoonlee/RSMix#1]
If all points are selected as in equation 7, why there are part point selected in figure 4?

**Comment by dogyoonlee** [comment]
Thank you for your interest, @cuge1995 !!
As I mentioned in the paper in Section 4.2, we randomly sampled the extracted points in subset to ensure the same number of points in mixed sample, preserving the overall shape of the subset. 
It also makes possible to cover the different densities of each samples making various samples.
However, If you want to use "not sampled data" in same batch, which means each data have the different number of points, you don't have to randomly sample the extracted points as we did.
