### ISSUE TITLE
Can you open source the supplementary material of your paper ?

### ISSUE THREAD

**Issue by cuge1995** [dogyoonlee/RSMix#2]

**Comment by dogyoonlee** [comment]
@cuge1995 
Sorry for the late reply. 

Yes, we open the supplementary material at CVPR open access page. 

Link: https://openaccess.thecvf.com/content/CVPR2021/html/Lee_Regularization_Strategy_for_Point_Cloud_via_Rigidly_Mixed_Sample_CVPR_2021_paper.html

I hope it would be helpful
