### ISSUE TITLE
How do You Visualize the Point Cloud?

### ISSUE THREAD

**Issue by ardianumam** [dogyoonlee/RSMix#3]
Hi!

Thanks for the great work. I wonder, how do you visualize the point cloud sample in the paper? It looks great and natural/ Do you use certain software? Thanks.

**Comment by dogyoonlee** [comment]
@ardianumam Thank you for your interest!!
I used the point cloud visualizer produced by [[pointnet++]](https://github.com/charlesq34/pointnet2)

If you have been confused about how to use the visualization tool from the above GitHub page,
it would be easier to use the tool uploaded on [[my GitHub page]](https://github.com/dogyoonlee/pointcloud_visualizer).

**Comment by ardianumam** [comment]
@dogyoonlee : Many thanks. I try and it works! But it's quite difficult to rotate the sample to get our desired point of view. Looks like there is no z-axis rotation? Any suggestion? Thanks.

**Comment by dogyoonlee** [comment]
@ardianumam Unfortunately, there is no explicit z-axis rotation. 
However, you can **indirectly get** the rotated object along the z-axis using x-axis and y-axis rotation sequentially. 
We just updated the implementation of [[my GitHub code]](https://github.com/dogyoonlee/pointcloud_visualizer/tree/main/pointcloud_visualization) for you to use the rotation with **keyboard event**(j, k, l, i buttons). 
I hope it would be helpful!!

**Comment by ardianumam** [comment]
@dogyoonlee : Awesome, many thanks!

**Comment by ardianumam** [comment]
Hi @dogyoonlee , I wonder how the coloring works? I pass my RGB color to `c_gt` parameter, and the final `c0`, `c1` and `c2` will be r,g,b channels with range of 0-255. But the colors are changed a lot, like my original orange color becomes green, etc. Thanks.

**Comment by dogyoonlee** [comment]
@ardianumam 
There can be confusing on the color values on visualization code.
As I remember, `c0`, `c1`, and `c2` represent the `Green`, `Red`, and `Blue` values, respectively.
Also, It is true that you can change the color of points by changing these values from 0-255.
I think now you can get the right color :)

**Comment by ardianumam** [comment]
@dogyoonlee : Yeah, thanks!
