### ISSUE TITLE
What is The Meaning of "Raw" in The Table?

### ISSUE THREAD

**Issue by ardianumam** [dogyoonlee/RSMix#4]
Hi, 

Thanks for the great work! I have some inquires:
1. As written in the title, what is the meaning of "Raw" in the Table 3 in the paper? Is it equal to "pre-aligned", "Unaligned", or something other? Could you confirm which dataset is specified as "Raw" in that table? Is it no [(1)](http://modelnet.cs.princeton.edu/ModelNet40.zip), [(2)](https://github.com/lmb-freiburg/orion) or [(3)](https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip)? The downloaded link are provided in the numbers, and I also put screenshot for each number below.
2. Or could you please provide the dataset links used in Table 3: (a) Pre-Aligned, (b) Unaligned and (c) Raw?

Many thanks :)

![image](https://user-images.githubusercontent.com/12822715/141648376-952a481a-adb2-431f-87e2-f10b3b0f8432.png)
![image](https://user-images.githubusercontent.com/12822715/141649034-1f4b5460-704b-4073-a0cb-ee300363908b.png)

**Comment by dogyoonlee** [comment]
@ardianumam 
I'm sorry for late reply and thank you for your interest to our work!!

1. 'Raw' means the original ModelNe40 dataset which are not preprocessed like 'pre-aligned' or 'unaligned'. 
In addition, you can find the detailed demonstration of 'pre-aligned' and 'unaligned' setting from [PointCNN](https://papers.nips.cc/paper/2018/hash/f5f8590cd58a54e94377e6ae2eded4d9-Abstract.html).

2. You can use Raw dataset from your above **(1)** link or the sampled point clouds dataset given by [pointnet++ repo](https://github.com/charlesq34/pointnet2/).
