### ISSUE TITLE
Benchmarking results of RSMix on Common Corruptions

### ISSUE THREAD

**Issue by jiachens** [dogyoonlee/RSMix#5]
Dear Authors,

Thank you so much for this nice repo. We recently proposed a new corruption robustness benchmark called ModelNet40-C and test RSMix on several corruptions from our dataset. We find that RSMix is robust to "density" corruptions. 
Github repo: https://github.com/jiachens/ModelNet40-C
Paper link: https://arxiv.org/abs/2201.12296

I wonder if you can mention our benchmark and dataset in your repo to highlight the results. Thank you!

**Comment by dogyoonlee** [comment]
@jiachens 
Thank you for your interest in our work!
I added the paper and github link on our repo's main page.

**Comment by jiachens** [comment]
Thank you so much!
